### ISSUE TITLE
Error when Connect

### ISSUE THREAD

**Issue by heltonspr** [QuickbaseAdmirer/QuickBase-C-Sharp-SDK#5]
Hello,

I used in my code the syntax:
var client = QuickBase.Login(username, password, domain);
 var application = client.Connect(appid, appToken);

But, since last month I can't connect and received the message: "Value 'multiuserid' requested not found."
"   em System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)\r\n   em System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)\r\n   em System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)\r\n   em Intuit.QuickBase.Client.QTable.LoadColumns(XPathNavigator xml) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QTable.cs:linha 305\r\n   em Intuit.QuickBase.Client.QTable.LoadColumns() na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QTable.cs:linha 295\r\n   em Intuit.QuickBase.Client.QTable.Load() na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QTable.cs:linha 279\r\n   em Intuit.QuickBase.Client.QTable..ctor(QColumnFactoryBase columnFactory, QRecordFactoryBase recordFactory, IQApplication application, String tableId) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QTable.cs:linha 21\r\n   em Intuit.QuickBase.Client.QTableFactory.CreateInstance(IQApplication application, String tableId) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QTableFactory.cs:linha 38\r\n   em Intuit.QuickBase.Client.QApplication.LoadTables() na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QApplication.cs:linha 296\r\n   em Intuit.QuickBase.Client.QApplication..ctor(QTableFactoryBase tableFactory, IQClient client, String applicationId, String token) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QApplication.cs:linha 37\r\n   em Intuit.QuickBase.Client.QApplicationFactory.CreateInstance(IQClient client, String applicationId, String token) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QApplicationFactory.cs:linha 28\r\n   em Intuit.QuickBase.Client.QClient.Connect(String applicationId, String token) na C:\\Projetos\\QBIntegration\\QuickBase-C-Sharp-SDK-master\\Intuit.QuickBase.Client\\QClient.cs:linha 69\r\n
 
I updated the project files, but the error not solved. 
Do you know how to solve this?

Tks,

Helton Ferreira

**Comment by BryceBarbara** [comment]
It's caused by the QuickBase C# SDK being horribly out of date. Some field types have been added since the SDK was last updated. If you open the "FieldType.cs" file in the Intuit.QuickBase.Core project, you can add "address", "multiuserid", and "multitext". That should allow you to connect to QuickBase servers once again.

**Comment by heltonspr** [comment]
Ok. Thanks a lot. Your recommendation solve the issue.
